[package]
name = "trespass"
version = "0.1.0"
authors = ["Zahari Petkov <zahari@balena.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
